version: "3.3"
services:
  db:
    build: 
      context: .
      dockerfile: pics_db.dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: