version: "3.3"
services:
  flask:
    build: 
      context: .
      dockerfile: flask.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    build: 
      context: .
      dockerfile: pics_db.dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  pic_daemon:
    build: 
      context: .
      dockerfile: flask.dockerfile
    volumes:
      - /tmp/pic_selector_local_s3_cache:/tmp/pic_selector_local_s3_cache
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: /webwork/run_pic_functions.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: